### ISSUE TITLE
support for zig's package manager

### ISSUE THREAD

**Issue by johan0A** [sbancuz/OpenMP-zig#1]
does this have support for zig's package manager ?

if yes I could not figure it out.
this does not work:
`build.zig:`
```zig
const OpenMP_zig_dep = b.dependency("OpenMP-zig", .{
    .target = target,
    .optimize = optimize,
});
exe.root_module.addImport("omp", OpenMP_zig_dep.module("omp"));
```
`build.zig.zon:`
```zig 

.dependencies = .{
    .@"OpenMP-zig" = .{
        .url = "https://github.com/sbancuz/OpenMP-zig/archive/refs/heads/master.zip",
        .hash = "1220b5ac4209d8e1be4e164e6d01917f9208f1a14670663405819061004062196e67",
    },
},
```

**Comment by sbancuz** [comment]
Tbh I was hoping it would work without testing it...

Regardless I should have fixed it. Can you tell me if it works for you now?

**Comment by johan0A** [comment]
I can import the module now but both `findOpenMP(b);` and `omp.linkSystemLibrary("omp", .{});` cant find openmp.

I'm on a debian based os and I just did `sudo apt-get install libomp-dev` to install openmp

**Comment by johan0A** [comment]
I can import the module now but both findOpenMP(b); and omp.linkSystemLibrary("omp", .{}); cant find openmp.

I'm on a debian based os and I just did sudo apt-get install libomp-dev to install openmp

**Comment by sbancuz** [comment]
I kinda get it why findOpenMP(b); doesn't find the library, but omp.linkSystemLibrary("omp", .{}); is strange since it's the standard function of the zig compiler. If you try to compile a normal c/c++ file with openmp does it work? If it does, what name does the shared library have? Because it should work with libomp.so which is the one provided with nix (at least)
